# Generated by Django 3.2.8 on 2021-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('test_at', models.DateTimeField(auto_now_add=True)),
                ('player_name', models.CharField(max_length=50)),
                ('flag_color', models.CharField(max_length=100)),
            ],
        ),
    ]
